/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lenovo
 */
public class Issue extends javax.swing.JFrame {

    /** Creates new form Issue */
    public Issue() {
        initComponents();
       show_user();
    }
    
    
 public ArrayList<Useri>userList(){
        ArrayList<Useri>usersList = new ArrayList<>();
        
         try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql1 =  "SELECT * FROM ISSUE";
    Statement st = connection.createStatement();
    ResultSet rs = st.executeQuery(sql1);
    
    Useri useri;
    
    while(rs.next())
    {
       useri= new Useri(rs.getInt("IssueId"),rs.getInt("StudentId"),rs.getString("StudentName"),rs.getInt("BookId"),rs.getString("BookName"),rs.getString("IssueDate"),rs.getString("ReturnDate"));
       usersList.add(useri);
    }
    
   // JOptionPane.showMessageDialog(null ,"Inserted Successfully");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        
         return usersList;
        
    }   
    
    
     public void show_user()
    {
        ArrayList<Useri> list = userList();
        DefaultTableModel model = (DefaultTableModel)issuetable.getModel();
        Object[] row = new Object[7];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getIssueId();
            row[1] =list.get(i).getStudentId();
            row[2]=list.get(i).getStudentName();
            row[3]=list.get(i).getBookId();
             row[4] =list.get(i).getBookName();
            row[5]=list.get(i).getIssueDate();
            row[6]=list.get(i).getReturnDate();
             model.addRow(row);
        }
    }

        public void show_user1()
    {
        ArrayList<Useri> list = userList();
        DefaultTableModel model = (DefaultTableModel)issuetable.getModel();
        Object[] row = new Object[7];
        
        for(int i=0;i<list.size();i++)
        {
           row[0]=list.get(i).getIssueId();
            row[1] =list.get(i).getStudentId();
            row[2]=list.get(i).getStudentName();
            row[3]=list.get(i).getBookId();
             row[4] =list.get(i).getBookName();
            row[5]=list.get(i).getIssueDate();
           row[6]=list.get(i).getReturnDate();
             
        }
        
        model.addRow(row);
    }
     

   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        studentid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        studentname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bookname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        issuetable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        issuedate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        returndate = new javax.swing.JTextField();
        issue = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("Issue Book");

        jLabel10.setBackground(new java.awt.Color(0, 51, 102));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("StudentID");

        studentid.setBackground(new java.awt.Color(0, 51, 102));
        studentid.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        studentid.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("StudentName");

        studentname.setBackground(new java.awt.Color(0, 51, 102));
        studentname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        studentname.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("BookID");

        bookid.setBackground(new java.awt.Color(0, 51, 102));
        bookid.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bookid.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("BookName");

        bookname.setBackground(new java.awt.Color(0, 51, 102));
        bookname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bookname.setForeground(new java.awt.Color(255, 255, 255));

        issuetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IssueID", "StudentID", "StudentName", "BookID", "BookName", "IssueDate", "ReturnDate"
            }
        ));
        issuetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuetableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(issuetable);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Issue Date");

        issuedate.setBackground(new java.awt.Color(0, 51, 102));
        issuedate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        issuedate.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Return Date");

        returndate.setBackground(new java.awt.Color(0, 51, 102));
        returndate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        returndate.setForeground(new java.awt.Color(255, 255, 255));

        issue.setBackground(new java.awt.Color(102, 0, 0));
        issue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        issue.setForeground(new java.awt.Color(255, 255, 255));
        issue.setText("ISSUE");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 0, 51));
        update.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 0, 51));
        delete.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sear.setBackground(new java.awt.Color(153, 0, 0));
        sear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sear.setForeground(new java.awt.Color(255, 255, 255));
        sear.setText("Search");
        sear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bookid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(studentid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issuedate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentname)
                            .addComponent(bookname)
                            .addComponent(returndate, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(sear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(753, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           Home obj = new Home();
                obj.setVisible(true);
                dispose();
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        // TODO add your handling code here:
        
        try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql =  "insert into ISSUE(StudentId ,StudentName,BookId,BookName,IssueDate,ReturnDate)values(?,?,?,?,?,?)";
    
    PreparedStatement pst = connection.prepareStatement(sql);
    
     pst.setString(1,studentid.getText());
      pst.setString(2,studentname.getText());
       pst.setString(3,bookid.getText());
        pst.setString(4,bookname.getText());
         pst.setString(5,issuedate.getText());
           pst.setString(6,returndate.getText());
         
           int k= pst.executeUpdate();
    
        
        if(k==1)
        {
             show_user1();
            JOptionPane.showMessageDialog(null ,"Inserted Successfully");
        }
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        
        
        
    }//GEN-LAST:event_issueActionPerformed

    private void issuetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuetableMouseClicked
        // TODO add your handling code here:
          int i= issuetable.getSelectedRow();
        TableModel model = issuetable.getModel();
        studentid.setText(model.getValueAt(i,1).toString());
        studentname.setText(model.getValueAt(i,2).toString());
         bookid.setText(model.getValueAt(i,3).toString());
          bookname.setText(model.getValueAt(i,4).toString());
        issuedate.setText(model.getValueAt(i,5).toString());
        returndate.setText(model.getValueAt(i,6).toString());
    }//GEN-LAST:event_issuetableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
        try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

           int row= issuetable.getSelectedRow();
   
           String value= (issuetable.getModel().getValueAt(row,0).toString());
           String query = "UPDATE ISSUE SET StudentId=? ,StudentName=?, BookId=?,BookName=? ,IssueDate=?, ReturnDate=? where IssueId="+value;
    
     PreparedStatement pst = connection.prepareStatement(query);
    
     pst.setString(1,studentid.getText());
      pst.setString(2,studentname.getText());
       pst.setString(3,bookid.getText());
        pst.setString(4,bookname.getText());
         pst.setString(5,issuedate.getText());
           pst.setString(6,returndate.getText());
          
        pst.executeUpdate();
     
        DefaultTableModel model = (DefaultTableModel)issuetable.getModel();
        model.setRowCount(0);
        
        show_user();
          JOptionPane.showMessageDialog(null ,"Updated Successfully");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
         try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

           int row= issuetable.getSelectedRow();
   
           String value= (issuetable.getModel().getValueAt(row,0).toString());
           String query = "DELETE FROM ISSUE where IssueId="+value;
           
            PreparedStatement pst = connection.prepareStatement(query);
              pst.executeUpdate();
     
        DefaultTableModel model = (DefaultTableModel)issuetable.getModel();
        model.setRowCount(0);
        
        show_user();
        JOptionPane.showMessageDialog(null ,"Deleted Successfully");
            
            }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql = " SELECT * FROM STUDENTS where StudentId=?";
    
    PreparedStatement pst = connection.prepareStatement(sql);
    pst.setString(1,studentid.getText());
    ResultSet rst = pst.executeQuery();
    
    if(rst.next())
    {
        String setname = rst.getString("Student_Name");
        studentname.setText(setname);
        
    }
         
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searActionPerformed
        // TODO add your handling code here:
        
         try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql = " SELECT * FROM ADDBOOKS where BookId=?";
    
    PreparedStatement pst = connection.prepareStatement(sql);
    pst.setString(1,bookid.getText());
    ResultSet rst = pst.executeQuery();
    
    if(rst.next())
    {
        String setname = rst.getString("BookName");
        bookname.setText(setname);
        
    }
         
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        
        
    }//GEN-LAST:event_searActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookname;
    private javax.swing.JButton delete;
    private javax.swing.JButton issue;
    private javax.swing.JTextField issuedate;
    private javax.swing.JTable issuetable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField returndate;
    private javax.swing.JButton sear;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField studentname;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
