/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lenovo
 */
public class Publisher extends javax.swing.JFrame {

    /** Creates new form Publisher */
    public Publisher() {
        initComponents();
        show_user();
    }

     public ArrayList<Userp>userList(){
        ArrayList<Userp>usersList = new ArrayList<>();
        
         try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql1 =  "SELECT * FROM PUBLISHER";
    Statement st = connection.createStatement();
    ResultSet rs = st.executeQuery(sql1);
    
    Userp userp;
    
    while(rs.next())
    {
       userp= new Userp(rs.getInt("PublisherId"),rs.getString("PublisherName"),rs.getString("PublisherAddress"),rs.getString("PublisherContact"));
       usersList.add(userp);
    }
    
   // JOptionPane.showMessageDialog(null ,"Inserted Successfully");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        
         return usersList;
        
    }   
    
      public void show_user()
    {
        ArrayList<Userp> list = userList();
        DefaultTableModel model = (DefaultTableModel)publishertable.getModel();
        Object[] row = new Object[4];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getPublisherId();
            row[1] =list.get(i).getPublisherName();
            row[2]=list.get(i).getPublisherAddress();
            row[3]=list.get(i).getPublisherContact();
             model.addRow(row);
        }
    }

        public void show_user1()
    {
        ArrayList<Userp> list = userList();
        DefaultTableModel model = (DefaultTableModel)publishertable.getModel();
        Object[] row = new Object[4];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getPublisherId();
            row[1] =list.get(i).getPublisherName();
            row[2]=list.get(i).getPublisherAddress();
            row[3]=list.get(i).getPublisherContact();
             
        }
        
        model.addRow(row);
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        publishername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        contact = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        publishertable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Publisher");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Publisher");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Contact");

        publishername.setBackground(new java.awt.Color(0, 51, 102));
        publishername.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        publishername.setForeground(new java.awt.Color(255, 255, 255));

        address.setBackground(new java.awt.Color(0, 51, 102));
        address.setColumns(20);
        address.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        contact.setBackground(new java.awt.Color(0, 51, 102));
        contact.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));

        add.setBackground(new java.awt.Color(0, 0, 51));
        add.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 0, 51));
        update.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 0, 51));
        delete.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        publishertable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        publishertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PublisherID", "PublisherName", "PublisherAddress", "PublisherContact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        publishertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publishertableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(publishertable);

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publishername, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publishername, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
         try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql =  "insert into PUBLISHER(PublisherName , PublisherAddress,PublisherContact )values(?,?,?)";
    
    PreparedStatement pst = connection.prepareStatement(sql);
    
     pst.setString(1,publishername.getText());
     
     pst.setString(2,address.getText());
     
     pst.setString(3,contact.getText());
     
        
    int k= pst.executeUpdate();
    
        
        if(k==1)
        {
             show_user1();
            JOptionPane.showMessageDialog(null ,"Inserted Successfully");
        }
        
    
    
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        

        
    }//GEN-LAST:event_addActionPerformed

    private void publishertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publishertableMouseClicked
        // TODO add your handling code here:
        
          int i= publishertable.getSelectedRow();
        TableModel model = publishertable.getModel();
        publishername.setText(model.getValueAt(i,1).toString());
        address.setText(model.getValueAt(i,2).toString());
         contact.setText(model.getValueAt(i,3).toString());
       
        
    }//GEN-LAST:event_publishertableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
        try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

           int row= publishertable.getSelectedRow();
   
           String value= (publishertable.getModel().getValueAt(row,0).toString());
           String query = "UPDATE PUBLISHER SET PublisherName=? ,PublisherAddress=?, PublisherContact=? where PublisherId="+value;
    
     PreparedStatement pst = connection.prepareStatement(query);
    
     pst.setString(1,publishername.getText());
      pst.setString(2,address.getText());
       pst.setString(3,contact.getText());
     
    
     
        pst.executeUpdate();
     
        DefaultTableModel model = (DefaultTableModel)publishertable.getModel();
        model.setRowCount(0);
        
        show_user();
          JOptionPane.showMessageDialog(null ,"Updated Successfully");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        

        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

           int row= publishertable.getSelectedRow();
   
           String value= (publishertable.getModel().getValueAt(row,0).toString());
           String query = "DELETE FROM PUBLISHER where PublisherId="+value;
           
            PreparedStatement pst = connection.prepareStatement(query);
              pst.executeUpdate();
     
        DefaultTableModel model = (DefaultTableModel)publishertable.getModel();
        model.setRowCount(0);
        
        show_user();
        JOptionPane.showMessageDialog(null ,"Deleted Successfully");
            
            }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         Home obj = new Home();
                obj.setVisible(true);
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Publisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Publisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Publisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Publisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Publisher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField contact;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField publishername;
    private javax.swing.JTable publishertable;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
