/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Return extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
        show_user();
    }

    
 public ArrayList<Usere>userList(){
        ArrayList<Usere>usersList = new ArrayList<>();
        
         try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql1 =  "SELECT * FROM RETURNBOOK";
    Statement st = connection.createStatement();
    ResultSet rs = st.executeQuery(sql1);
    
    Usere usere;
    
    while(rs.next())
    {
       usere= new Usere(rs.getInt("ReturnId"),rs.getInt("StudentId"),rs.getString("StudentName"),rs.getInt("BookId"),rs.getString("BookName"),rs.getString("IssueDate"),rs.getString("ReturnDate"));
       usersList.add(usere);
    }
    
   // JOptionPane.showMessageDialog(null ,"Inserted Successfully");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        
         return usersList;
        
    }   
    
    
     public void show_user()
    {
        ArrayList<Usere> list = userList();
        DefaultTableModel model = (DefaultTableModel)returntable.getModel();
        Object[] row = new Object[7];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getReturnId();
            row[1] =list.get(i).getStudentId();
            row[2]=list.get(i).getStudentName();
            row[3]=list.get(i).getBookId();
             row[4] =list.get(i).getBookName();
            row[5]=list.get(i).getIssueDate();
            row[6]=list.get(i).getReturnDate();
             model.addRow(row);
        }
    }

        public void show_user1()
    {
        ArrayList<Usere> list = userList();
        DefaultTableModel model = (DefaultTableModel)returntable.getModel();
        Object[] row = new Object[7];
        
        for(int i=0;i<list.size();i++)
        {
           row[0]=list.get(i).getReturnId();
            row[1] =list.get(i).getStudentId();
            row[2]=list.get(i).getStudentName();
            row[3]=list.get(i).getBookId();
             row[4] =list.get(i).getBookName();
            row[5]=list.get(i).getIssueDate();
           row[6]=list.get(i).getReturnDate();
             
        }
        
        model.addRow(row);
    }
     

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stdid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stdname = new javax.swing.JTextField();
        bid = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        issued = new javax.swing.JTextField();
        returned = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        returntable = new javax.swing.JTable();
        ret = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Return Book");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Student ID");

        stdid.setBackground(new java.awt.Color(0, 51, 102));
        stdid.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        stdid.setForeground(new java.awt.Color(255, 255, 255));
        stdid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stdidKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Student Name");

        stdname.setBackground(new java.awt.Color(0, 51, 102));
        stdname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        stdname.setForeground(new java.awt.Color(255, 255, 255));

        bid.setBackground(new java.awt.Color(0, 51, 102));
        bid.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bid.setForeground(new java.awt.Color(255, 255, 255));

        bname.setBackground(new java.awt.Color(0, 51, 102));
        bname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bname.setForeground(new java.awt.Color(255, 255, 255));

        issued.setBackground(new java.awt.Color(0, 51, 102));
        issued.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        issued.setForeground(new java.awt.Color(255, 255, 255));

        returned.setBackground(new java.awt.Color(0, 51, 102));
        returned.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        returned.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Book ID");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Book Name");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Issue Date");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Return Date");

        returntable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        returntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ReturnID", "StudentID", "StudentName", "BookID", "BookName", "IssueDate", "ReturnDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(returntable);

        ret.setBackground(new java.awt.Color(102, 0, 0));
        ret.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ret.setForeground(new java.awt.Color(255, 255, 255));
        ret.setText("Return");
        ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(153, 0, 0));
        search.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(search)
                                        .addGap(254, 254, 254))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabel2)
                                                .addGap(42, 42, 42)
                                                .addComponent(stdid, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jButton4)
                                                .addGap(173, 173, 173)
                                                .addComponent(ret, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(137, 137, 137)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1)
                                .addGap(341, 341, 341)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(issued)
                            .addComponent(bname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returned, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(stdname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issued, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(returned, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4)
                                        .addComponent(ret))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(stdid, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(search)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         Home obj = new Home();
                obj.setVisible(true);
                dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void stdidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdidKeyReleased
        // TODO add your handling code here:
        
         
        
        
    }//GEN-LAST:event_stdidKeyReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
        try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql = " SELECT * FROM ISSUE where StudentId=?";
    
    PreparedStatement pst = connection.prepareStatement(sql);
    pst.setString(1,stdid.getText());
    ResultSet rst = pst.executeQuery();
    
    if(rst.next())
    {
        String setname = rst.getString("StudentName");
        stdname.setText(setname);
        
        String setbookid = rst.getString("BookId");
        bid.setText(setbookid);
        
        String setbookname = rst.getString("BookName");
        bname.setText(setbookname);
        
        String setissue = rst.getString("IssueDate");
        issued.setText(setissue);
        
        String setreturn = rst.getString("ReturnDate");
        returned.setText(setreturn);
        
    }
         
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
        
        
    }//GEN-LAST:event_searchActionPerformed

    private void retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retActionPerformed
        // TODO add your handling code here:
        
         try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql =  "insert into RETURNBOOK(StudentId ,StudentName,BookId,BookName,IssueDate,ReturnDate)values(?,?,?,?,?,?)";
    
    PreparedStatement pst = connection.prepareStatement(sql);
    
     pst.setString(1,stdid.getText());
      pst.setString(2,stdname.getText());
       pst.setString(3,bid.getText());
        pst.setString(4,bname.getText());
         pst.setString(5,issued.getText());
           pst.setString(6,returned.getText());
         
           int k= pst.executeUpdate();
    
        
        if(k==1)
        {
             show_user1();
            JOptionPane.showMessageDialog(null ,"Inserted Successfully");
        }
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null ,e);
        }
         
        try{
            String url = "jdbc:sqlserver://RAFANPC\\SQLEXPR:1433;databaseName=Project";

            String user = "sa";
            String password = "123456789";
            
            Connection connection = DriverManager.getConnection(url,user,password);

    String sql = " DELETE FROM ISSUE where StudentId=?";
                
    PreparedStatement pst = connection.prepareStatement(sql);
    pst.setString(1,stdid.getText());
    ResultSet rst = pst.executeQuery();
    
   
      
        }catch(Exception e)
        {
           // JOptionPane.showMessageDialog(null ,e);
             JOptionPane.showMessageDialog(null ,"Inserted Successfully");
        }  
         
        
    }//GEN-LAST:event_retActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bname;
    private javax.swing.JTextField issued;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ret;
    private javax.swing.JTextField returned;
    private javax.swing.JTable returntable;
    private javax.swing.JButton search;
    private javax.swing.JTextField stdid;
    private javax.swing.JTextField stdname;
    // End of variables declaration//GEN-END:variables
}
